### ISSUE TITLE
 'STDMAERunner' object has no attribute 'to_running_device'

### ISSUE THREAD

**Issue by QHofmann** [Jimmy-7664/STD_MAE#3]
AttributeError: 'STDMAERunner' object has no attribute 'to_running_device'

**Comment by QHofmann** [comment]
There is a similar method in STEP's code, and its implementation simply transfers the data to the gpu or cpu, so I think here as well

**Comment by NonCover** [comment]
> There is a similar method in STEP's code, and its implementation simply transfers the data to the gpu or cpu, so I think here as well

How to fix it?

**Comment by QHofmann** [comment]
把数据放到gpu上就可以，建立同名的函数




Moonlight.
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jimmy-7664/STD_MAE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月26日(星期二) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jimmy-7664/STD_MAE]  'STDMAERunner' object has no attribute 'to_running_device' (Issue #3)





  
There is a similar method in STEP's code, and its implementation simply transfers the data to the gpu or cpu, so I think here as well
  
How to fix it?

**Comment by NonCover** [comment]
> 把数据放到gpu上就可以，建立同名的函数 Moonlight. ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jimmy-7664/STD_MAE" ***@***.***&gt;; 发送时间:&nbsp;2024年3月26日(星期二) 下午3:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Jimmy-7664/STD_MAE] 'STDMAERunner' object has no attribute 'to_running_device' (Issue #3) There is a similar method in STEP's code, and its implementation simply transfers the data to the gpu or cpu, so I think here as well How to fix it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;



> 把数据放到gpu上就可以，建立同名的函数 Moonlight. ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jimmy-7664/STD_MAE" ***@***.***&gt;; 发送时间:&nbsp;2024年3月26日(星期二) 下午3:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Jimmy-7664/STD_MAE] 'STDMAERunner' object has no attribute 'to_running_device' (Issue #3) There is a similar method in STEP's code, and its implementation simply transfers the data to the gpu or cpu, so I think here as well How to fix it? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

> 搞定了。但新的问题出现了。

**Comment by Jimmy-7664** [comment]
Dear all, sorry for the late respone. I just test STD-MAE on a totally new Linux Server. It works well.
This issue seems also related to the package version. Please make sure that you use the same version as the requirements.txt, especially the package easytorch not torch. Moreover,` I recommend to create a new conda environment to test this repo.

**Comment by Jimmy-7664** [comment]
@NonCover @QHofmann 
Dear all, sorry for the bother. I find the reason behind this issue. I placed an error package in requirements.txt. Please use `pip uninstall easytorch` to uninstall the package `easytorch`. The right package name is `easy_torch`. I already fix the `requirements.txt`file now. Or you can create a new conda environment to install the package through the new `requirements.txt` file.
